arch/Cargo.toml, arch/src/cortex_m/mod.rs, examples/nrf52/microbit-rak811/Cargo.toml, examples/nrf52/microbit-uart/Cargo.toml, rt/Cargo.toml, rt/src/platform/cortex_m/mod.rs, rt/src/platform/cortex_m/nrf/gpiote/mod.rs, rt/src/platform/cortex_m/nrf/timer.rs, rt/src/platform/cortex_m/nrf/uarte.rs
* Rename thumbv6 -> isa+thumbv6
* Use chip+nrf51 and chip+nrf52833 instead of old format
* Only support chips we know will work
=> Add initial example for nrf51 devkit

examples/common/lora/src/lib.rs, examples/stm32l0/lora-discovery/src/main.rs, rt/src/api/lora.rs, rt/src/driver/lora/rak811.rs, rt/src/driver/lora/sx127x/mod.rs, rt/src/system/device.rs
Split driver into an "actor", "controller", and "interrupt" component.
The interrupt component receives interrupts and passes on the appropriate
event to the controller component.
The controller component receives messages from interrupt and timers and
provides responses to commands issues by the actor component.
The actor component forwards commands to the controller components and
awaits the state processing to complete before responding to the user.
Implement receive in LoRa API
=> Split sx127x driver into actor and controller

examples/stm32f4/esp8266/Cargo.toml, rt/Cargo.toml
This (hopefully) fixes CI by pinning the stm32f4xx-hal version is the most recent released (April 5th).
@jcrossley3 Could you check if the example still works?
=> Pin stm32f4xx-hal to version 0.9

examples/nrf52/microbit-esp8266/.cargo/config, examples/nrf52/microbit-rak811/.cargo/config, examples/nrf52/microbit-uart/.cargo/config, examples/stm32l0xx/.cargo/config
This is what is done in embassy's .cargo/config.toml's
And we already have the required "rust-src" component pulled in by the rust-toolchain.toml file.
This change reduces the size of the binary of the micro-bit-esp8266 example from 778K to 170K
=> Add build-std = core to .cargo/config.toml's

device/src/actors/mod.rs, device/src/actors/wifi/esp8266/mod.rs, device/src/actors/wifi/mod.rs, device/src/drivers/wifi/esp8266/mod.rs, device/src/kernel/actor.rs, examples/common/wifi/src/lib.rs, examples/nrf52/microbit-esp8266/src/main.rs, examples/std/esp8266/src/main.rs, examples/stm32l0xx/lora-discovery/src/app.rs, examples/stm32l0xx/lora-discovery/src/lora.rs
* Add generic WiFi actor abstraction that works with any driver
implementing the WifiSupplicant and TcpStack traits
* Add types for WifiAdapter and Socket to simplify usage of actor
* Migrate examples to use actor version
=> Create generic WiFi actor abstractions

device/Cargo.toml, device/src/drivers/lora/rak811/mod.rs, device/src/drivers/wifi/esp8266/mod.rs, device/src/kernel/mod.rs, device/src/lib.rs, examples/common/wifi/Cargo.lock, examples/nrf52/microbit-esp8266/Cargo.lock, examples/nrf52/microbit-esp8266/Cargo.toml, examples/nrf52/microbit-rak811/Cargo.lock, examples/nrf52/microbit-rak811/Cargo.toml, examples/nrf52/microbit-uart/Cargo.lock, examples/nrf52/microbit-uart/Cargo.toml, examples/rp/blinky/Cargo.lock, examples/rp/blinky/Cargo.toml, examples/std/esp8266/Cargo.lock, examples/std/esp8266/Cargo.toml, examples/std/hello/Cargo.lock, examples/std/hello/Cargo.toml, examples/stm32l0xx/lora-discovery/Cargo.lock, examples/stm32l0xx/lora-discovery/Cargo.toml, examples/wasm/browser/Cargo.lock, examples/wasm/browser/Cargo.toml
Replace the channel implementation using the new one from embassy. Actor channel is still using the existing implementation, mainly due to not yet finding a way to use const generics from assoc types.
=> Replace mpsc

README.md, device/src/actors/led/matrix.rs, device/src/actors/led/mod.rs, device/src/actors/lora/mod.rs, device/src/actors/ticker.rs, device/src/actors/timer.rs, device/src/actors/wifi/mod.rs, device/src/kernel/actor.rs, device/src/testutil.rs, device/src/traits/ip.rs, device/src/traits/wifi.rs, device/tests/integration_tests.rs, docs/modules/ROOT/pages/drivers.adoc, examples/common/wifi/src/lib.rs, examples/nrf52/microbit/rak811/src/app.rs, examples/nrf52/microbit/uart/src/statistics.rs, examples/std/hello/src/myactor.rs, examples/stm32h7/nucleo-h743zi/blinkdance/src/main.rs, examples/stm32h7/nucleo-h743zi/blinky/src/main.rs, examples/stm32l0/lora-discovery/src/app.rs
Prevent the possibility of accidentally responding before a message is processed. Introduce an InboxMessage
type that ensures an owned message is not used beyond that of the response signal
Introduce a Default trait requirement for Responses to ensure safe default handling.
=> Ensure message is not alive after response is sent

device/Cargo.toml, device/src/drivers/lora/sx127x/mod.rs, device/src/drivers/lora/sx127x/sx127x_lora/mod.rs, device/src/drivers/lora/sx127x/sx127x_radio.rs, examples/common/wifi/Cargo.lock, examples/nrf52/microbit/esp8266/Cargo.lock, examples/nrf52/microbit/rak811/Cargo.lock, examples/nrf52/microbit/uart/Cargo.lock, examples/rp/pico/blinky/Cargo.lock, examples/std/esp8266/Cargo.lock, examples/std/hello/Cargo.lock, examples/stm32h7/nucleo-h743zi/blinkdance/Cargo.lock, examples/stm32h7/nucleo-h743zi/blinky/Cargo.lock, examples/stm32h7/nucleo-h743zi/epd/Cargo.lock, examples/stm32h7/nucleo-h743zi/esp8266/Cargo.lock, examples/stm32l0/lora-discovery/Cargo.lock, examples/stm32l0/lora-discovery/src/main.rs, examples/wasm/browser/Cargo.lock
Various optimizations that reduce static RAM requirements by 20% for lora-discovery.
=> Remove temporary stack allocated buffer when transmitting

.gitignore, examples/_build/Cargo.lock, examples/_build/Cargo.toml, examples/_build/src/lib.rs, examples/nrf52/microbit/Cargo.lock, examples/nrf52/microbit/ble-temperature/build.rs, examples/nrf52/microbit/compass/build.rs, examples/nrf52/microbit/esp8266/build.rs, examples/nrf52/microbit/rak811/build.rs, examples/nrf52/microbit/uart/build.rs, examples/rp/pico/Cargo.lock, examples/rp/pico/blinky/build.rs, examples/std/Cargo.lock, examples/std/cloud/build.rs, examples/std/esp8266/build.rs, examples/stm32h7/nucleo-h743zi/Cargo.lock, examples/stm32h7/nucleo-h743zi/ethernet/build.rs, examples/stm32l0/lora-discovery/Cargo.lock, examples/stm32l0/lora-discovery/build.rs, examples/stm32l1/rak811/Cargo.lock, examples/stm32l1/rak811/build.rs, examples/stm32l4/iot01a-wifi/Cargo.lock, examples/stm32l4/iot01a-wifi/build.rs, examples/stm32wl/nucleo-wl55/Cargo.lock, examples/stm32wl/nucleo-wl55/build.rs
Configuration entries are pulled from the `.drogue/config.toml` found
beneath $HOME and the project manifest directory, typically
$PWD. Additionally, all the latter's parents will be
searched. Precendence is determined by the order of calls to
Config::merge(), so we start from the root and search down through the
manifest dir components i.e. last merge "wins". The
`.drogue/config.toml` beneath $HOME has the lowest precendence.
We also fail the compile if any entries are missing like we used
to. We can give a little better error message referencing
`.drogue/config.toml` and the missing value.
The next step is to create a proc macro that can query the
now-lazily-created static CONFIG hashmap and avoid all the file
inclusion of the files we're still creating from the CONFIG entries.
=> Refactor configuration to support more config file locations

device/src/drivers/led/mod.rs
This commit contains a suggestion to use `PinState::from` and
`PinState::not` in `ActiveHigh::set` and `ActiveLow::set` to reduce/simplify
these functions.
=> Use PinState::from/not in ActiveHigh/ActiveLow

examples/apps/drogue-temperature/Cargo.toml
This commit removes patch.creates-io from
examples/apps/drogue-temperature/Cargo.toml as this is currently causing
the following warning:
```console
warning: patch for the non root package will be ignored, specify patch
at the workspace root:
package: examples/apps/drogue-temperature/Cargo.toml
workspace: drogue-device/Cargo.toml
```
Removing seems like the correct thing to do as this app is included as a
member of the workspace in the root Cargo.toml and will inherit/use that
files patch.crates-io.
=> Remove patch.crates-io table from temperature app

examples/apps/blinky/src/lib.rs
The commit add a missing slash in the doc for the
BlinkyConfiguration struct which is causing the generated text to not
include that last line.
The docs for `apps/blinky` can be generated using the following command:
```console
$ cargo doc --features "embassy/time embassy/time-tick-32768hz" --package bsp-blinky-app:0.1.0 --open
```
=> Add missing slash to BlinkyConfiguration doc

device/src/lib.rs
This commit fixes a typo and also makes two doc comments into "normal"
code comments to avoid the following two warnings:
```console
warning: unused doc comment
--> counter/src/main.rs:50:5
|
50 |       /// Mounting the Actor will spawn an embassy task
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
51 | /     let addr = COUNTER.mount(spawner, Counter {
52 | |         count: 0
53 | |     });
| |_______- rustdoc does not generate documentation for statements
|
= note: `#[warn(unused_doc_comments)]` on by default
= help: use `//` for a plain comment
warning: unused doc comment
--> counter/src/main.rs:55:5
|
55 |     /// The actor address may be used in any embassy task to
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|     communicate with the actor.
| …
```
=> Fix typo and warnings in Counter example

device/src/kernel/actor.rs
This commit removes part of the doc comment for on_mount that refers to
the configuration parameter which I think was removed in
Commit de176e921ddf7eaf8f31d98912850f616b06d0bf ("Refactor actor context and simplify actor configuration").
=> Remove configuration from Actor::on_mount doc

examples/apps/blinky/src/lib.rs
This commit suggests changing the name of the led variable to
led_address, and app to app_address, to (hopefully) improve
the readability of the code.
The motivation for this change was that I had to look up that
ActorContext's mount function returns an Address, and perhaps others
that are new to the code base will have the same issue.
=> Change led/app variables to have _address suffix

device/src/bsp/mod.rs
This commit adds a module comment to the bsp module to help users like
myself who might not be familiar with the acronym BSP.
=> Add module comment to bsp module

device/src/bsp/boards/nrf52/adafruit_feather_sense.rs, device/src/bsp/boards/nrf52/microbit.rs, device/src/bsp/boards/stm32h7/nucleo_h743zi.rs, device/src/bsp/boards/stm32l0/lora_discovery.rs, device/src/bsp/boards/stm32l1/rak811.rs, device/src/bsp/boards/stm32l4/iot01a.rs, device/src/bsp/boards/stm32u5/b_u585i_iot02a.rs, device/src/bsp/boards/stm32wl/nucleo_wl55.rs, device/src/bsp/mod.rs
This commit adds an associated type named `BoardConfig` to the `Board` trait.
The intention of this is to allow a Board to be created with a
configuration object specific to that board by using the `new_with_config`
constructor function.
A default implementation is provided for `new_with_config`, for Boards that
don't have a configuration. For those boards that don't have a config the
unit type (`()`) is set as the `BoardConfig` value.
Refs: https://github.com/drogue-iot/drogue-device/issues/169
=> Add BoardConfig type to Board trait

README.md
This commit adds badges for the CI build.yaml and test.yaml workflow
as the current badge (ci.yaml) does not exist any more.
=> Add workflow badges for CI build and test

device/src/kernel/actor.rs
This commit makes Actor::mount delegate to Actor::initialize instead
of containing the initialization code itself.
=> Make Actor::mount delegate to Actor::initialize

device/Cargo.toml, device/src/drivers/ble/mesh/configuration_manager.rs, examples/nrf52/nrf52840-dk/Cargo.lock
The no-std and v4 features are incompatible, so following this guide:
https://docs.rs/uuid/1.0.0-alpha.1/uuid/#embedded
=> Use crate to ensure valid uuid's, i.e. proper version & variant

device/src/drivers/ble/mesh/pdu/access.rs
This commit uses Self to be consistent with other methods in this file.
=> Use Self for consistency in access.rs

examples/nrf52/nrf52840-dk/Cargo.lock, examples/nrf52/nrf52840-dk/Cargo.toml
Currently, the following warning is generated when building the ble-mesh
example:
```console
warning: Patch `embassy-boot v0.1.0 (https://github.com/embassy-rs/embassy.gitrev=3d6b8bd9832d5a29cab4aa21434663e6ea6f4488#3d6b8bd9)` was not used in the crate graph.
```
I think this dependency is used by the bootloader-dfu example which has
this dependency in its Cargo.toml, so it seems safe to remove it from
the shared parent Cargo.toml.
=> Remove embassy-boot patch from nrf52840-dk

device/src/drivers/ble/mesh/model/mod.rs
Currently, the following warnings are generated:
```console
warning: unused imports: `CONFIGURATION_CLIENT`, `CONFIGURATION_SERVER`
--> device/src/drivers/ble/mesh/model/mod.rs:3:5
|
3 |     CONFIGURATION_CLIENT, CONFIGURATION_SERVER,
|     ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused imports: `GENERIC_BATTERY_CLIENT`, `GENERIC_BATTERY_SERVER`, `GENERIC_ONOFF_CLIENT`, `GENERIC_ONOFF_SERVER`
--> device/src/drivers/ble/mesh/model/mod.rs:6:15
|
6 |     battery::{GENERIC_BATTERY_CLIENT, GENERIC_BATTERY_SERVER},
|               ^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^
7 |     onoff::{GENERIC_ONOFF_CLIENT, GENERIC_ONOFF_SERVER},
|             ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^
warning: `drogue-device` (lib) generated …
```
=> Suppress unsued imports in model/mod.rs

device/src/drivers/ble/mesh/driver/elements/mod.rs, device/src/drivers/ble/mesh/driver/mod.rs, device/src/drivers/ble/mesh/driver/node/context.rs, device/src/drivers/ble/mesh/driver/node/mod.rs, device/src/drivers/ble/mesh/driver/pipeline/mesh.rs, device/src/drivers/ble/mesh/driver/pipeline/mod.rs, device/src/drivers/ble/mesh/driver/pipeline/provisioned/network/authentication.rs, device/src/drivers/ble/mesh/driver/pipeline/unprovisioned/provisioning_bearer.rs, device/src/drivers/ble/mesh/driver/pipeline/unprovisioned/segmentation/mod.rs, device/src/drivers/ble/mesh/generic_provisioning.rs
Remove gratuitous `async` markers where not necessary.
=> Split pipeline into relevant halves with an inner enum.

examples/nrf52/microbit/compass/Cargo.lock, examples/nrf52/microbit/compass/Cargo.toml, examples/nrf52/microbit/jukebox/Cargo.lock, examples/nrf52/microbit/jukebox/Cargo.toml, examples/nrf52/nrf52840-dk/.cargo/config.toml
This commit attempts to fix a couple of build warnings that are
currently being generated:
```console
warning: unused config key `unstable.namespaced-features` in
`/drougue/drogue-device/examples/nrf52/nrf52840-dk/.cargo/config.toml`
warning: Patch `nrf-softdevice v0.1.0
(https://github.com/embassy-rs/nrf-softdevice.git?rev=\c584deaf9d9e941f18457934a4a463e078f380ec#c584deaf)` was not used in the crate graph.
```
=> Suppress build warnings

examples/nrf52/adafruit-nrf-feather/neopixel/Cargo.lock, examples/nrf52/adafruit-nrf-feather/neopixel/Cargo.toml
Currently, the following build error is generated when running cargo
build in examples/nrf52/adafruit-nrf-feather/neopixel:
```console
Building /drogue-device/examples/nrf52/adafruit-nrf-feather/neopixel
$ cargo build --release
Updating git repository `https://github.com/embassy-rs/embassy.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`
Caused by:
failed to load source for dependency `embassy`
Caused by:
Unable to update https://github.com/embassy-rs/embassy.git?rev=6a3b3ca755073f73b24fad89a109fba7132d1312#6a3b3ca7
Caused by:
object not found - no match for id (6a3b3ca755073f73b24fad89a109fba7132d1312); class=Odb (9); code=NotFound (-3)
Error: command `cargo build --release` failed, exit status: 101
```
I've not looked into why this commit is no …
=> Update embassy commit rev for neopixel example

device/Cargo.toml, device/build.rs, device/src/drivers/ble/mesh/config/configuration_manager.rs, device/src/firmware/mod.rs, docs/modules/ROOT/examples/basic/Cargo.lock, examples/apps/lorawan/Cargo.lock, examples/apps/update/Cargo.toml, examples/nrf52/adafruit-feather-nrf52840/bootloader/Cargo.lock, examples/nrf52/adafruit-feather-nrf52840/bt-mesh/Cargo.lock, examples/nrf52/adafruit-feather-nrf52840/neopixel/Cargo.lock, examples/nrf52/microbit/ble/Cargo.lock, examples/nrf52/microbit/ble/Cargo.toml, examples/nrf52/microbit/ble/README.adoc, examples/nrf52/microbit/ble/src/main.rs, examples/nrf52/microbit/compass/Cargo.lock, examples/nrf52/microbit/esp8266/Cargo.lock, examples/nrf52/microbit/jukebox/Cargo.lock, examples/nrf52/microbit/uart/Cargo.lock, examples/nrf52/nrf52840-dk/ble-mesh/Cargo.lock, examples/rp/pico/Cargo.lock, examples/std/Cargo.lock, examples/stm32h7/nucleo-h743zi/Cargo.lock, examples/stm32l0/lora-discovery/Cargo.lock, examples/stm32l1/rak811/Cargo.lock, examples/stm32l4/iot01a/Cargo.lock, examples/stm32u5/iot02a/Cargo.lock, examples/stm32wl/nucleo-wl55/Cargo.lock, examples/wasm/browser/Cargo.lock
* Set cortex_m feature based on target architecture
* Match on cortex_m flag rather than feature flag
* Remove serial portion of update example
* Use latest embedded-update
bors r+
=> Several fixes to cortex m and dfu

examples/nrf52/adafruit-feather-nrf52840/bootloader/README.adoc, examples/nrf52/microbit/bootloader/README.adoc, examples/stm32l4/iot01a/bootloader/README.adoc, examples/stm32wl/nucleo-wl55/bootloader/README.adoc
These files are referenced as .adoc, but are actually .md. This is why the docs
fail to build (now).
=> fix: convert files to asciidoc

examples/stm32l0/lora-discovery/Cargo.toml
This commit suggest temporarily disabling LTO for
stm32l0/lora-discovery as it currently fails to build and produces the
following error:
```console
$ cargo b --release
Compiling drogue-device v0.1.0 (/home/danielbevenius/work/drougue/drogue-device/device)
Compiling drogue-lorawan-app v0.1.0 (/home/danielbevenius/work/drougue/drogue-device/examples/apps/lorawan)
Compiling lora-discovery v0.1.0 (/home/danielbevenius/work/drougue/drogue-device/examples/stm32l0/lora-discovery)
error: linking with `rust-lld` failed: exit status: 1
|
= note: "rust-lld" "-flavor" "gnu" "/tmp/rustcE0o7dO/symbols.o" "/home/danielbevenius/work/drougue/drogue-device/examples/stm32l0/lora-discovery/target/thumbv6m-none-eabi/release/deps/lora_discovery-121397784992859f.lora_discovery.44cd7467-cgu.0.rcgu.o" …
```
=> Disable LTO for stm32l0/lora-discovery

device/src/drivers/wifi/esp8266/mod.rs
This commit suggests adding a closure that can be used in all the
map_err functions in the configure method.
=> Add a closure to map_err in ESP8266 configure

device/src/drivers/dns.rs
This commit updates `try_parse_ip` to enumerate over the split string
with the motivation to avoid some code duplication.
=> Use enumerate in try_parse_ip

examples/stm32wl/nucleo-wl55/Cargo.lock, examples/stm32wl/nucleo-wl55/bootloader/Cargo.toml
This commit changes the name of this crate to be
`nucleo-wl55-bootloader` instead of `iot01a-bootloader`.
The motivation for this change is that there another crate with the same name in `/examples/stm32l4/iot01a/bootloader`.
And when building the EclipseCon 2022 Hackaton firmware the following warning is generated:
```console
$ cargo b --release
warning: skipping duplicate package `iot01a-bootloader` found at `/.cargo/git/checkouts/drogue-device-5b9868033e74c452/05ef609/examples/stm32l4/iot01a/bootloader`
```
I've verified is by manually changing the name of the nucleo-wl55-bootloader in the git checkouts directory and the warning is gone. I looks like the dependency microbit-bsp is causing this and I'm guessing here that all of the Cargo.toml files are parsed for this dependency (git …
=> Change bootloader name to nucleo-wl55-bootloader

examples/rp2040/pico-w/Cargo.lock, examples/rp2040/pico-w/Cargo.toml, examples/rp2040/pico-w/README.adoc, examples/rp2040/pico-w/src/fmt.rs, examples/rp2040/pico-w/src/main.rs
Enables the new USB logger from embassy to make the example log output to USB serial so that it can be used without a debug probe.
=> feat: support uf2 firmware for pico

boards/adafruit-feather-nrf52/src/board.rs, examples/nrf52/adafruit-feather-nrf52840/boot/src/main.rs
This allows for configuring the interrupt priority when running with softdevice, as well as avoids duplicate symbol error when the original configure method is in scope.
=> Move QSPI interrupt initialization out of the configure method
